apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stickytux-frontend
  labels:
    app: stickytux
    component: frontend
spec:
  to:
    kind: Service
    name: stickytux-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stickytux-backend
  labels:
    app: stickytux
    component: backend
spec:
  to:
    kind: Service
    name: stickytux-backend
  port:
    targetPort: http
  path: /api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect