apiVersion: v1
kind: Service
metadata:
  name: stickytux-backend
  labels:
    app: stickytux
    component: backend
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: stickytux
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: stickytux-frontend
  labels:
    app: stickytux
    component: frontend
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: stickytux
    component: frontend